#!/usr/bin/env perl

use strict;
use warnings;
use 5.014;

use File::Slurp qw(read_file);
use Getopt::Long;

our $VERSION = '0.00';

my $template = 'bon-tmpl.eps';
my $opt      = {};

GetOptions(
	$opt,
	qw{
	  account=s
	  amount=i
	  bank=s
	  date=s
	  person=s
	  separef=s
	  receiptdorf
	  receiptmail
	  mail1=s
	  mail2=s
	  mail3=s
	  },
);

$opt->{account} //= q{};
$opt->{amount}  //= q{     };
$opt->{bank}    //= q{};
$opt->{date}    //= q{};
$opt->{person}  //= q{};
$opt->{separef} //= 'FIXME';
$opt->{mail1}   //= q{};
$opt->{mail2}   //= q{};
$opt->{mail3}   //= q{};

my $default_font     = 'Courier-Bold';
my $default_fontsize = 15;
my $cfg              = {
	account => {
		value  => $opt->{account},
		offset => [ 5, 265 ],
	},
	amount5 => {
		value => substr( $opt->{amount}, -1, 1 ) // q{},
		offset => [ 134, 423 ],
	},
	amount4 => {
		value => substr( $opt->{amount}, -2, 1 ) // q{},
		offset => [ 118, 423 ],
	},
	amount3 => {
		value => substr( $opt->{amount}, -3, 1 ) // q{},
		offset => [ 90, 423 ],
	},
	amount2 => {
		value => substr( $opt->{amount}, -4, 1 ) // q{},
		offset => [ 72, 423 ],
	},
	amount1 => {
		value => substr( $opt->{amount}, -5, 1 ) // q{},
		offset => [ 54, 423 ],
	},
	bank => {
		value  => $opt->{bank},
		offset => [ 5, 230 ],
	},
	date => {
		value    => $opt->{date},
		offset   => [ 160, 105 ],
		font     => 'Courier',
		fontsize => 12,
	},
	person => {
		value  => $opt->{person},
		offset => [ 5, 250 ],
	},
	separef => {
		value => $opt->{separef},
		offset => [ 72, 448 ],
		font => 'Courier',
		fontsize => 12,
	},
	receiptdorf => {
		value => $opt->{receiptdorf} ? 'X' : q{},
		offset => [ 7, 130 ],
	},
	receiptmail => {
		value => $opt->{receiptmail} ? 'X' : q{},
		offset => [ 7, 100 ],
	},
	mail1 => {
		value  => $opt->{mail1},
		offset => [ 5, 67 ],
	},
	mail2 => {
		value  => $opt->{mail2},
		offset => [ 5, 35 ],
	},
	mail3 => {
		value  => $opt->{mail3},
		offset => [ 5, 5 ],
	},
};

for my $line ( read_file($template) ) {
	chomp $line;
	if ( $line eq 'showpage' ) {
		for my $key ( keys %{$cfg} ) {
			printf(
				"/%s %s selectfont\n",
				$cfg->{$key}->{font} // $default_font,
				$cfg->{$key}->{fontsize} // $default_fontsize
			);
			printf( "%d %d moveto\n", @{ $cfg->{$key}->{offset} } );
			printf( "(%s) show\n",    $cfg->{$key}->{value} );
		}
	}
	say $line;
}

__END__

=head1 NAME

=head1 SYNOPSIS

=head1 VERSION

=head1 DESCRIPTION

=head1 OPTIONS

=over

=back

=head1 EXIT STATUS

=head1 CONFIGURATION

None.

=head1 DEPENDENCIES

=over

=back

=head1 BUGS AND LIMITATIONS

=head1 AUTHOR

Copyright (C) 2013 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>

=head1 LICENSE

  0. You just DO WHAT THE FUCK YOU WANT TO.
