#!/bin/sh

(
echo 23 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio23/direction
for i in {1..20}; do
	echo 1 > /sys/class/gpio/gpio23/value
	sleep 0.5
	echo 0 > /sys/class/gpio/gpio23/value
	sleep 0.5
done
) &
